name: Testing DANN-cfDNA model fitting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        conda env create -f DANN_cfDNA_env.yml

    - name: Run tests for DANN-cfDNA modeling fitting
      shell: bash -l {0}
      run: |
        conda run -n DANN_cfDNA_env pip install pytest pytest-cov
        conda run -n DANN_cfDNA_env pytest --junitxml=test_results.xml --cov=DANN_cfDNA --cov-report=xml tests/

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test_results
        path: test_results.xml

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage_report
        path: coverage.xml